### ISSUE TITLE
Creating the project with Vivado

### ISSUE THREAD

**Issue by grymoire** [securelyfitz/WTFpga#2]
It's somewhat difficult to go through the exercises when the first step in the manual/class  is to 
"Choose  WTFPGA under  Recent Projects to open up the project we’ll start with"
I've tried to open an existing project, and using your repository, Vivado doesn't find any existing projects. There is no create_project.tcl script like the Digilent examples.
I've created a project and tried to import some files but I'm not sure I did it right. There were many directories.

It would also be a good idea to warn people trying to prepare for an upcoming class about the disk space requirements. I needed 58GB of disk space on my Linux system, but I only learned about this after waiting 2 hours for the download of the installer to finish.. 

Thank you for the course, btw.

**Comment by securelyfitz** [comment]
thanks, good catch. the manual was originally made for when i brought laptops with me to class. I've updated and added clarifications to the "DIY" section of the readme in 7b6454847c32eb4eabc8ef6cdddd00ca2d18c11b

let me know if you have any more trouble. Good luck!

**Comment by grymoire** [comment]
Thanks. The setup has been a little challenging. The tutorials are based on
4-year-old Vivado software, and there are gotcha's like 1-2 hour downloads
to only discover that my Linux system needs 60GB of free disk space before
it can install Vivado.

I can take some notes of the things I've found and send them to you.

**Comment by securelyfitz** [comment]
i appreciate the offer - but in all reality, the icebreaker/open toolchain route is the future of this workshop. the effort involved in keeping up with xilinx tools and the availability of the right boards has been tough from a maintenance perspective as well as for learners

**Comment by grymoire** [comment]
For sure. Vivado is a big beast.
